export const skillImage = {
  JavaScript: "/images/skill/JavaScript.svg",
  TypeScript: "/images/skill/TypeScript.svg",
  HTML: "/images/skill/HTML.svg",
  CSS: "/images/skill/CSS.svg",
  React: "/images/skill/React.svg",
  Redux: "/images/skill/Redux.svg",
  NextJS: "/images/skill/NextJS.svg",
  NodeJS: "/images/skill/NodeJS.svg",
  Express: "/images/skill/Express.svg",
  TailwindCSS: "/images/skill/TailwindCSS.svg",
  MUI: "/images/skill/Mui.svg",
  StyledComponents: "/images/skill/Styled.svg",
  FramerMotion: "/images/skill/Motion.svg",
  Vite: "/images/skill/Vite.svg",
  Bun: "/images/skill/Bun.svg",
  Figma: "/images/skill/Figma.svg",
  Git: "/images/skill/Git.svg",
  Jira: "/images/skill/Jira.svg",
};